### ISSUE TITLE
Marked as deprecated and not selectable in package management

### ISSUE THREAD

**Issue by RubenKruiswijk** [splittingred/modActiveDirectory#1]
On the package page on http://modxcms.com/extras/package/711 it says: This version has been marked as deprecated. Please use a newer version.

But I cann't find a newer version. Are there problems with the current one? Is there any activity on this project? We would really like to use this package.

**Comment by splittingred** [comment]
Updated, there were some problems with the extension_packages setting and some other issues that required me to pull it down. Is fixed and updated now.
