### ISSUE TITLE
Regarding LDAP_OPT_REFERRALS

### ISSUE THREAD

**Issue by ghost** [splittingred/modActiveDirectory#3]
I've noticed that class.adldap.php and modactivedirectorydriver.class both set LDAP_OPT_REFERRALS differently... to 0 and 1, respectively.

https://github.com/splittingred/modActiveDirectory/blob/develop/core/components/activedirectory/model/activedirectory/class.adldap.php#L345

https://github.com/splittingred/modActiveDirectory/blob/develop/core/components/activedirectory/model/activedirectory/modactivedirectorydriver.class.php#L162

A particular problem arises, with an intuitive/minimal modActiveDirectory configuration, when searching against a Windows 2003 Domain Controller in that ldap_search() will error out unless LDAP_OPT_REFERRALS is set to 0, e.g. modactivedirectorydriver.class.php : 529 - PHP warning: ldap_search(): Search: Operations error. This issue is also explained in more detail here: http://www.php.net/manual/en/function.ldap-search.php#45388

As a result, the Auto-Add User Groups functionality may not work as expected for certain setups.

I can think of two suggestions:

1.) Consistently set LDAP_OPT_REFERRALS to 0  in this mod.
2.) Make LDAP_OPT_REFERRALS a System Setting option, with a safe default.

I have verified that suggestion 1 corrects the issue, and is an easy fix, but I understand that suggestion 2 may be more desirable.

Please advise.

Thanks. -Keith

**Comment by splittingred** [comment]
Will be in 1.0.1 release as a System Setting, defaulting to 0.
